[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "imse440"
authors = [{name = "Fred Feng", email = "fredfeng@umich.edu"}]
dynamic = ["version", "description"]
